server:
  port: 8090
  forward-headers-strategy: native
  error:
    include-message: always

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  devtools:
    add-properties: false
  output:
    ansi:
      enabled: always
  datasource:
    type: com.zaxxer.hikari.HikariDataSource

    # MySQL配置好数据库连接信息，项目初始化会执行安装程序（MySQL 版本需 5.7 以上）
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://127.0.0.1:3306/halo?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    #    username: root
    #    password: root

    # H2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:${halo.work-dir}/db/halo
    username: admin
    password: 123456

  h2:
    console:
      settings:
        web-allow-others: false
      path: /h2-console
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
      location: ${java.io.tmpdir}
      resolve-lazily: true

management:
  endpoints:
    web:
      base-path: /api/admin/actuator
      exposure:
        include: ['httptrace', 'metrics', 'env', 'logfile', 'health']

logging:
  level:
    run.halo.app: INFO
  file:
    path: ${halo.work-dir}/logs

springfox:
  documentation:
    enabled: false

halo:
  download-timeout: 5m
  cache: memory
  work-dir: ${user.home}/.imusk/halo/